export const seasonData = [
  {
    losses: 23,
    ot_losses: 5,
    team: "Tampa Bay Lightning",
    wins: 54,
  },
  {
    losses: 18,
    ot_losses: 11,
    team: "Nashville Predators",
    wins: 53,
  },
  {
    losses: 20,
    ot_losses: 10,
    team: "Winnipeg Jets",
    wins: 52,
  },
  {
    losses: 24,
    ot_losses: 7,
    team: "Vegas Golden Knights",
    wins: 51,
  },
  {
    losses: 20,
    ot_losses: 12,
    team: "Boston Bruins",
    wins: 50,
  },
  {
    losses: 26,
    ot_losses: 7,
    team: "Toronto Maple Leafs",
    wins: 49,
  },
  {
    losses: 26,
    ot_losses: 7,
    team: "Washington Capitals",
    wins: 49,
  },
  {
    losses: 29,
    ot_losses: 6,
    team: "Pittsburgh Penguins",
    wins: 47,
  },
  {
    losses: 26,
    ot_losses: 11,
    team: "Minnesota Wild",
    wins: 45,
  },
  {
    losses: 27,
    ot_losses: 10,
    team: "San Jose Sharks",
    wins: 45,
  },
  {
    losses: 30,
    ot_losses: 7,
    team: "Columbus Blue Jackets",
    wins: 45,
  },
  {
    losses: 29,
    ot_losses: 8,
    team: "Los Angeles Kings",
    wins: 45,
  },
  {
    losses: 25,
    ot_losses: 13,
    team: "Anaheim Ducks",
    wins: 44,
  },
  {
    losses: 30,
    ot_losses: 8,
    team: "Florida Panthers",
    wins: 44,
  },
  {
    losses: 29,
    ot_losses: 9,
    team: "New Jersey Devils",
    wins: 44,
  },
  {
    losses: 32,
    ot_losses: 6,
    team: "St. Louis Blues",
    wins: 44,
  },
  {
    losses: 30,
    ot_losses: 9,
    team: "Colorado Avalanche",
    wins: 43,
  },
  {
    losses: 26,
    ot_losses: 14,
    team: "Philadelphia Flyers",
    wins: 42,
  },
  {
    losses: 32,
    ot_losses: 8,
    team: "Dallas Stars",
    wins: 42,
  },
  {
    losses: 35,
    ot_losses: 10,
    team: "Calgary Flames",
    wins: 37,
  },
  {
    losses: 35,
    ot_losses: 11,
    team: "Carolina Hurricanes",
    wins: 36,
  },
  {
    losses: 40,
    ot_losses: 6,
    team: "Edmonton Oilers",
    wins: 36,
  },
  {
    losses: 37,
    ot_losses: 10,
    team: "New York Islanders",
    wins: 35,
  },
  {
    losses: 39,
    ot_losses: 9,
    team: "New York Rangers",
    wins: 34,
  },
  {
    losses: 39,
    ot_losses: 10,
    team: "Chicago Blackhawks",
    wins: 33,
  },
  {
    losses: 40,
    ot_losses: 11,
    team: "Vancouver Canucks",
    wins: 31,
  },
  {
    losses: 39,
    ot_losses: 13,
    team: "Detroit Red Wings",
    wins: 30,
  },
  {
    losses: 41,
    ot_losses: 12,
    team: "Arizona Coyotes",
    wins: 29,
  },
  {
    losses: 40,
    ot_losses: 13,
    team: "Montreal Canadiens",
    wins: 29,
  },
  {
    losses: 43,
    ot_losses: 11,
    team: "Ottawa Senators",
    wins: 28,
  },
  {
    losses: 45,
    ot_losses: 12,
    team: "Buffalo Sabres",
    wins: 25,
  },
];
